### ISSUE TITLE
rapidfuzz里面找不到string_metric，导致在pretrain测试的时候中断

### ISSUE THREAD

**Issue by Huangqqqhhh** [mxin262/SwinTextSpotter#101]
[09/02 19:07:09] d2.evaluation.evaluator INFO: Total inference time: 0:08:48.902549 (3.647604 s / img per device, on 2 devices)
[09/02 19:07:09] d2.evaluation.evaluator INFO: Total inference pure compute time: 0:01:17 (0.536733 s / img per device, on 2 devices)
[09/02 19:07:11] d2.evaluation.text_evaluation INFO: Saving results to ./output/inference/text_results.json
[09/02 19:07:18] d2.engine.train_loop ERROR: Exception during training:
Traceback (most recent call last):
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/engine/train_loop.py", line 141, in train
    self.after_step()
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/engine/train_loop.py", line 171, in after_step
    h.after_step()
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/engine/hooks.py", line 370, in after_step
    self._do_eval()
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/engine/hooks.py", line 345, in _do_eval
    results = self._func()
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/engine/defaults.py", line 400, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/engine/defaults.py", line 552, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/evaluation/evaluator.py", line 180, in inference_on_dataset
    results = evaluator.evaluate()
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/evaluation/text_evaluation.py", line 363, in evaluate
    text_result = self.evaluate_with_official_code(result_path, self._text_eval_gt_path) # None
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/evaluation/text_evaluation.py", line 332, in evaluate_with_official_code
    return text_eval_script.text_eval_main(det_file=result_path, gt_file=gt_path, is_word_spotting=self._word_spotting)
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/evaluation/text_eval_script.py", line 472, in text_eval_main
    return rrc_evaluation_funcs.main_evaluation(None,det_file, gt_file, default_evaluation_params,validate_data,evaluate_method)
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/evaluation/rrc_evaluation_funcs.py", line 415, in main_evaluation
    evalData = evaluate_method_fn(p['g'], p['s'], evalParams)
  File "/home/hhq/data/code/SwinTextSpotter/detectron2/evaluation/text_eval_script.py", line 381, in evaluate_method
    edd = string_metric.levenshtein(gtTrans[gtNum].upper(), detTrans[detNum].upper())
NameError: name 'string_metric' is not defined

还有就是请问这是在window系统上实现的嘛

**Comment by mxin262** [comment]
版本问题，可以试试更低的版本

**Comment by wu-yz** [comment]
应该是版本太高了，可以卸载rapidfuzz，装一个1.6.0的

**Comment by Huangqqqhhh** [comment]
可以加个联系方式嘛，一起讨论
&nbsp;


权是海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月10日(星期二) 晚上7:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mxin262/SwinTextSpotter] rapidfuzz里面找不到string_metric，导致在pretrain测试的时候中断 (Issue #101)





 
应该是版本太高了，可以卸载rapidfuzz，装一个1.6.0的

**Comment by Huangqqqhhh** [comment]
请问你复现成功了嘛？IC15的测试json注释文件好像用不了


权是海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mxin262/SwinTextSpotter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月10日(星期二) 晚上7:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mxin262/SwinTextSpotter] rapidfuzz里面找不到string_metric，导致在pretrain测试的时候中断 (Issue #101)





 
应该是版本太高了，可以卸载rapidfuzz，装一个1.6.0的
