### ISSUE TITLE
Environment Installations Failed

### ISSUE THREAD

**Issue by cpc0401** [mxin262/SwinTextSpotter#31]
I use Anaconda for installation, and there are no errors until the step `python setup.py build develop`.
And the command line cannot compile successfully.

The following are the errors that I faced.
```
running build
running build_py
running build_ext
C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xb5 in position 107: invalid start byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'detectron2._C' extension
Emitting ninja build file C:\Users\hank\Desktop\Intern\SwinTextSpotter\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\hank\Desktop\Intern\SwinTextSpotter\detectron2\layers\csrc -IC:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\include -IC:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\include\TH -IC:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\hank\anaconda3\envs\SWINS\include -IC:\Users\hank\anaconda3\envs\SWINS\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c C:\Users\hank\Desktop\Intern\SwinTextSpotter\detectron2\layers\csrc\deformable\deform_conv_cuda.cu -o C:\Users\hank\Desktop\Intern\SwinTextSpotter\build\temp.win-amd64-3.8\Release\Users\hank\Desktop\Intern\SwinTextSpotter\detectron2\layers\csrc\deformable\deform_conv_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
FAILED: C:/Users/hank/Desktop/Intern/SwinTextSpotter/build/temp.win-amd64-3.8/Release/Users/hank/Desktop/Intern/SwinTextSpotter/detectron2/layers/csrc/deformable/deform_conv_cuda.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\hank\Desktop\Intern\SwinTextSpotter\detectron2\layers\csrc -IC:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\include -IC:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\include\TH -IC:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -IC:\Users\hank\anaconda3\envs\SWINS\include -IC:\Users\hank\anaconda3\envs\SWINS\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c C:\Users\hank\Desktop\Intern\SwinTextSpotter\detectron2\layers\csrc\deformable\deform_conv_cuda.cu -o C:\Users\hank\Desktop\Intern\SwinTextSpotter\build\temp.win-amd64-3.8\Release\Users\hank\Desktop\Intern\SwinTextSpotter\detectron2\layers\csrc\deformable\deform_conv_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
C:/Users/hank/anaconda3/envs/SWINS/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

C:/Users/hank/anaconda3/envs/SWINS/lib/site-packages/torch/include\ATen/core/boxing/impl/boxing.h(100): warning: integer conversion resulted in a change of sign

C:/Users/hank/anaconda3/envs/SWINS/lib/site-packages/torch/include\ATen/record_function.h(13): warning: modifier is ignored on an enum specifier

C:/Users/hank/anaconda3/envs/SWINS/lib/site-packages/torch/include\ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign

C:/Users/hank/anaconda3/envs/SWINS/lib/site-packages/torch/include\torch/csrc/jit/ir/ir.h(1347): error: member "torch::jit::ProfileOptionalOp::Kind" may not be initialized

1 error detected in the compilation of "C:/Users/hank/AppData/Local/Temp/tmpxft_00012a20_00000000-7_deform_conv_cuda.cpp1.ii".
deform_conv_cuda.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\utils\cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 189, in <module>
    setup(
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\utils\cpp_extension.py", line 643, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\utils\cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\Users\hank\anaconda3\envs\SWINS\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
Hoping that anyone can help.

**Comment by BakingBrains** [comment]
@cpc0401 It needs CUDA 11.1, 10.1 won't work as expected.
