### ISSUE TITLE
显示在'detectron2.layers'中找不到'move_device_like'文件

### ISSUE THREAD

**Issue by GaoShuang98** [mxin262/SwinTextSpotter#73]
显示找不到'move_device_like'文件,我早您的项目里面也没有找到该文件,请问您那有这个文件吗?报错如下:
Traceback (most recent call last):
  File "E:\Pytorch_code\SwinTextSpotter\demo\demo.py", line 14, in <module>
    from predictor import VisualizationDemo
  File "E:\Pytorch_code\SwinTextSpotter\demo\predictor.py", line 10, in <module>
    from detectron2.engine.defaults import DefaultPredictor
  File "E:\Pytorch_code\SwinTextSpotter\detectron2\engine\__init__.py", line 12, in <module>
    from .defaults import *
  File "E:\Pytorch_code\SwinTextSpotter\detectron2\engine\defaults.py", line 35, in <module>
    from detectron2.modeling import build_model
  File "E:\Pytorch_code\SwinTextSpotter\detectron2\modeling\__init__.py", line 4, in <module>
    from .anchor_generator import build_anchor_generator, ANCHOR_GENERATOR_REGISTRY
  File "E:\Pytorch_code\SwinTextSpotter\detectron2\modeling\anchor_generator.py", line 9, in <module>
    from detectron2.layers import ShapeSpec, move_device_like
ImportError: cannot import name 'move_device_like' from 'detectron2.layers' (E:\Pytorch_code\SwinTextSpotter\detectron2\layers\__init__.py)

**Comment by mxin262** [comment]
这可能是系统的问题
